import type { SupabaseClient } from "@supabase/supabase-js";
import type { LabelData } from "../types/label";
import type { Product } from "../types/product";
import { formatPtDate, parsePtDate, ptDateToIsoDate } from "./date";
import { DEFAULT_SERIAL_START } from "./sscc";
import { getSupabaseBrowserClient } from "./supabase";

const DRAFT_LABEL_KEY = "warehouse-label-printer:draft-label";
const SELECTED_PRODUCT_KEY = "warehouse-label-printer:selected-product";
const PRINT_HISTORY_KEY = "warehouse-label-printer:print-history";
const SSCC_SERIAL_KEY = "warehouse-label-printer:sscc-serial";
const LABEL_DEFAULTS_KEY = "warehouse-label-printer:label-defaults";
const PRINT_HISTORY_LIMIT = 500;

export type LabelDefaults = {
  data_entrega?: string;
  ordem_compra?: string;
};

type SupabaseLabelRow = {
  id: string;
  product_id: string | null;
  product_snapshot: Product;
  ordem_compra: string;
  lote: string;
  data_entrega: string | null;
  data_validade: string | null;
  validade_texto: string;
  validade_barras: string;
  caixas: number;
  quantidade_etiquetas: number;
  sscc: string;
  auchan_validity_status: LabelData["auchan_validity_status"] | null;
  auchan_days_available: number | null;
  auchan_days_margin: number | null;
  auchan_minimum_days: number | null;
  printed_at: string | null;
  created_at: string;
};

function canUseStorage(): boolean {
  return typeof window !== "undefined" && Boolean(window.localStorage);
}

function readJson<T>(key: string, fallback: T): T {
  if (!canUseStorage()) {
    return fallback;
  }

  const stored = window.localStorage.getItem(key);

  if (!stored) {
    return fallback;
  }

  try {
    return JSON.parse(stored) as T;
  } catch {
    return fallback;
  }
}

function writeJson(key: string, value: unknown): void {
  if (!canUseStorage()) {
    return;
  }

  window.localStorage.setItem(key, JSON.stringify(value));
}

export function setSelectedProduct(product: Product): void {
  writeJson(SELECTED_PRODUCT_KEY, product);
}

export function getSelectedProduct(): Product | null {
  return readJson<Product | null>(SELECTED_PRODUCT_KEY, null);
}

export function clearSelectedProduct(): void {
  if (canUseStorage()) {
    window.localStorage.removeItem(SELECTED_PRODUCT_KEY);
  }
}

export function saveDraftLabel(label: LabelData): void {
  writeJson(DRAFT_LABEL_KEY, label);
}

export function getDraftLabel(): LabelData | null {
  return readJson<LabelData | null>(DRAFT_LABEL_KEY, null);
}

export function clearDraftLabel(): void {
  if (canUseStorage()) {
    window.localStorage.removeItem(DRAFT_LABEL_KEY);
  }
}

export function getNextSSCCSerial(): number {
  if (!canUseStorage()) {
    return DEFAULT_SERIAL_START;
  }

  const stored = Number(window.localStorage.getItem(SSCC_SERIAL_KEY) ?? DEFAULT_SERIAL_START);
  const serial = Number.isFinite(stored) && stored >= DEFAULT_SERIAL_START ? stored : DEFAULT_SERIAL_START;

  // For real warehouse production, SSCC should be generated by a central backend/database to avoid duplicates across devices.
  window.localStorage.setItem(SSCC_SERIAL_KEY, String(serial + 1));

  return serial;
}

export async function reserveNextSSCCSerial(): Promise<number> {
  const supabase = getSupabaseBrowserClient();

  if (!supabase) {
    return getNextSSCCSerial();
  }

  const { data, error } = await supabase.rpc("reserve_next_sscc_serial");
  const serial = Number(data);

  if (error || !Number.isInteger(serial) || serial < DEFAULT_SERIAL_START) {
    console.warn("Could not reserve Supabase SSCC serial, using local counter.", error);
    return getNextSSCCSerial();
  }

  return serial;
}

export function getPrintHistory(): LabelData[] {
  return readJson<LabelData[]>(PRINT_HISTORY_KEY, []).filter(isStoredLabel);
}

export function recordPrintHistory(label: LabelData): void {
  const history = getPrintHistory();
  const deduped = history.filter((item) => item.id !== label.id);
  writeJson(PRINT_HISTORY_KEY, [label, ...deduped].slice(0, PRINT_HISTORY_LIMIT));
}

function formatStoredDate(value: string | null): string {
  if (!value) {
    return "";
  }

  const date = parsePtDate(value);

  return date ? formatPtDate(date) : value;
}

function labelToSupabaseRow(label: LabelData) {
  return {
    id: label.id,
    product_id: label.product.id,
    product_snapshot: label.product,
    ordem_compra: String(label.ordem_compra ?? ""),
    lote: String(label.lote ?? ""),
    data_entrega: ptDateToIsoDate(String(label.data_entrega ?? "")),
    data_validade: ptDateToIsoDate(String(label.validade_texto ?? "")),
    validade_texto: String(label.validade_texto ?? ""),
    validade_barras: String(label.validade_barras ?? ""),
    caixas: Number(label.caixas) || 0,
    quantidade_etiquetas: Number(label.quantidade_etiquetas) || 1,
    sscc: String(label.sscc ?? ""),
    auchan_validity_status: label.auchan_validity_status ?? null,
    auchan_days_available: label.auchan_days_available ?? null,
    auchan_days_margin: label.auchan_days_margin ?? null,
    auchan_minimum_days: label.auchan_minimum_days ?? null,
    printed_at: new Date().toISOString(),
    created_at: label.created_at,
  };
}

function isStoredLabel(value: unknown): value is LabelData {
  if (!value || typeof value !== "object") {
    return false;
  }

  const label = value as LabelData;

  return (
    typeof label.id === "string" &&
    typeof label.created_at === "string" &&
    typeof label.sscc === "string" &&
    Boolean(label.product) &&
    typeof label.product === "object" &&
    typeof label.product.id === "string" &&
    typeof label.product.name === "string"
  );
}

function labelFromSupabaseRow(row: SupabaseLabelRow): LabelData {
  return {
    id: row.id,
    product: row.product_snapshot,
    ordem_compra: row.ordem_compra,
    lote: row.lote,
    data_entrega: formatStoredDate(row.data_entrega),
    validade_texto: row.validade_texto || formatStoredDate(row.data_validade),
    validade_barras: row.validade_barras,
    caixas: row.caixas,
    quantidade_etiquetas: row.quantidade_etiquetas,
    sscc: row.sscc,
    auchan_validity_status: row.auchan_validity_status ?? undefined,
    auchan_days_available: row.auchan_days_available,
    auchan_days_margin: row.auchan_days_margin,
    auchan_minimum_days: row.auchan_minimum_days,
    created_at: row.created_at,
  };
}

function mergePrintHistories(...histories: LabelData[][]): LabelData[] {
  const labelsById = new Map<string, LabelData>();

  for (const history of histories) {
    for (const label of history) {
      labelsById.set(label.id, label);
    }
  }

  return Array.from(labelsById.values())
    .sort((left, right) => Date.parse(right.created_at) - Date.parse(left.created_at))
    .slice(0, PRINT_HISTORY_LIMIT);
}

async function loadLabelsTableHistory(supabase: SupabaseClient): Promise<LabelData[]> {
  const { data, error } = await supabase
    .from("labels")
    .select(
      "id, product_id, product_snapshot, ordem_compra, lote, data_entrega, data_validade, validade_texto, validade_barras, caixas, quantidade_etiquetas, sscc, auchan_validity_status, auchan_days_available, auchan_days_margin, auchan_minimum_days, printed_at, created_at",
    )
    .order("printed_at", { ascending: false, nullsFirst: false })
    .order("created_at", { ascending: false })
    .limit(PRINT_HISTORY_LIMIT);

  if (error || !data) {
    return [];
  }

  return (data as SupabaseLabelRow[]).map(labelFromSupabaseRow);
}

async function uploadLabelsTableHistory(supabase: SupabaseClient, labels: LabelData[]): Promise<void> {
  if (labels.length === 0) {
    return;
  }

  const { error } = await supabase.from("labels").upsert(labels.map(labelToSupabaseRow), { onConflict: "id" });

  if (error) {
    console.warn("Could not sync structured Supabase label history.", error);
  }
}

export async function loadPrintHistoryFromSource(): Promise<LabelData[]> {
  const supabase = getSupabaseBrowserClient();

  if (!supabase) {
    return getPrintHistory();
  }

  const labelsTableHistory = await loadLabelsTableHistory(supabase);
  const remoteHistory = mergePrintHistories(labelsTableHistory);

  writeJson(PRINT_HISTORY_KEY, remoteHistory);

  return remoteHistory;
}

export function getLocalLabelDefaults(): LabelDefaults {
  return readJson<LabelDefaults>(LABEL_DEFAULTS_KEY, {});
}

export function saveLocalLabelDefaults(defaults: LabelDefaults): void {
  writeJson(LABEL_DEFAULTS_KEY, { ...getLocalLabelDefaults(), ...defaults });
}

export async function loadLabelDefaults(): Promise<LabelDefaults> {
  const localDefaults = getLocalLabelDefaults();
  const supabase = getSupabaseBrowserClient();

  if (!supabase) {
    return localDefaults;
  }

  const { data, error } = await supabase.from("app_defaults").select("key, value").in("key", ["data_entrega", "ordem_compra"]);

  if (error || !data) {
    console.warn("Could not load Supabase defaults, using local defaults.", error);
    return localDefaults;
  }

  const remoteDefaults = data.reduce<LabelDefaults>((defaults, item) => {
    const key = String(item.key);

    if (key === "data_entrega" || key === "ordem_compra") {
      defaults[key] = String(item.value ?? "");
    }

    return defaults;
  }, {});

  return { ...localDefaults, ...remoteDefaults };
}

export async function saveLabelDefaults(defaults: LabelDefaults): Promise<void> {
  saveLocalLabelDefaults(defaults);

  const supabase = getSupabaseBrowserClient();

  if (!supabase) {
    return;
  }

  const rows = Object.entries(defaults)
    .filter(([, value]) => value)
    .map(([key, value]) => ({
      key,
      value,
      updated_at: new Date().toISOString(),
    }));

  if (rows.length === 0) {
    return;
  }

  const { error } = await supabase.from("app_defaults").upsert(rows, { onConflict: "key" });

  if (error) {
    console.warn("Could not save Supabase defaults.", error);
  }
}

export async function recordPrintHistoryToSource(label: LabelData): Promise<void> {
  recordPrintHistory(label);

  const supabase = getSupabaseBrowserClient();

  if (!supabase) {
    return;
  }

  await uploadLabelsTableHistory(supabase, [label]);
}
