import type { LabelData } from "../types/label";
import type { Product } from "../types/product";
import { DEFAULT_SERIAL_START } from "./sscc";

const DRAFT_LABEL_KEY = "warehouse-label-printer:draft-label";
const SELECTED_PRODUCT_KEY = "warehouse-label-printer:selected-product";
const PRINT_HISTORY_KEY = "warehouse-label-printer:print-history";
const SSCC_SERIAL_KEY = "warehouse-label-printer:sscc-serial";

function canUseStorage(): boolean {
  return typeof window !== "undefined" && Boolean(window.localStorage);
}

function readJson<T>(key: string, fallback: T): T {
  if (!canUseStorage()) {
    return fallback;
  }

  const stored = window.localStorage.getItem(key);

  if (!stored) {
    return fallback;
  }

  try {
    return JSON.parse(stored) as T;
  } catch {
    return fallback;
  }
}

function writeJson(key: string, value: unknown): void {
  if (!canUseStorage()) {
    return;
  }

  window.localStorage.setItem(key, JSON.stringify(value));
}

export function setSelectedProduct(product: Product): void {
  writeJson(SELECTED_PRODUCT_KEY, product);
}

export function getSelectedProduct(): Product | null {
  return readJson<Product | null>(SELECTED_PRODUCT_KEY, null);
}

export function clearSelectedProduct(): void {
  if (canUseStorage()) {
    window.localStorage.removeItem(SELECTED_PRODUCT_KEY);
  }
}

export function saveDraftLabel(label: LabelData): void {
  writeJson(DRAFT_LABEL_KEY, label);
}

export function getDraftLabel(): LabelData | null {
  return readJson<LabelData | null>(DRAFT_LABEL_KEY, null);
}

export function clearDraftLabel(): void {
  if (canUseStorage()) {
    window.localStorage.removeItem(DRAFT_LABEL_KEY);
  }
}

export function getNextSSCCSerial(): number {
  if (!canUseStorage()) {
    return DEFAULT_SERIAL_START;
  }

  const stored = Number(window.localStorage.getItem(SSCC_SERIAL_KEY) ?? DEFAULT_SERIAL_START);
  const serial = Number.isFinite(stored) && stored >= DEFAULT_SERIAL_START ? stored : DEFAULT_SERIAL_START;

  // For real warehouse production, SSCC should be generated by a central backend/database to avoid duplicates across devices.
  window.localStorage.setItem(SSCC_SERIAL_KEY, String(serial + 1));

  return serial;
}

export function getPrintHistory(): LabelData[] {
  return readJson<LabelData[]>(PRINT_HISTORY_KEY, []);
}

export function recordPrintHistory(label: LabelData): void {
  const history = getPrintHistory();
  const deduped = history.filter((item) => item.id !== label.id);
  writeJson(PRINT_HISTORY_KEY, [label, ...deduped].slice(0, 100));
}
